### ISSUE TITLE
Bonus Menu Settings

### ISSUE THREAD

**Issue by luut3** [vcu-cmsc355-f17/android-app-seth-and-the-bois#4]
-As a DND Home Brewery user
-So that I can change users or report bugs
-I want a menu options that lets me logout or report bugs

Scenarios
A. Feature: Contact Us (Test case called ContactUsTest.java)
	     -Given I am on the character select screen
	     -When I click on the menu icon
	     -Then the menu screen will expand
	     -When I click Contact Us
	     -Then it will take us to a google forms that allows us to enter information
B. Feature: Logout (Test case called LogoutTest.java)
	     -Given I am on the character select screen
             -When I click on the menu icon
             -Then the menu screen will expand
	     -When I click logout
	     -Then I will be signed out of the app and be brought back to the welcome screen
C. Feature: Change User (Test case called ChangeUserTest.java)
             -Given I am on the character select screen
             -When I click on the menu icon
             -Then the menu screen will expand	     
             -When I click change user
	     -Then I will be on the welcome screen prompted to to select gmail, twitter, or guest login
	     -When I select one of them, enter login information, and hit login
	     -Then I will be on the profile screen

**Comment by delarosaae** [comment]
https://goo.gl/forms/ibrh7EXuDXDXd1WN2

This is the url for the goolge forms for feedback
